CREATE TABLE IF NOT EXISTS STORY13_PROJECTION (
  EVENT_ID VARCHAR(96) PRIMARY KEY,
  WORKSPACE_ID VARCHAR(96) NOT NULL,
  AGGREGATE_ID VARCHAR(128) NOT NULL,
  AGGREGATE_VERSION BIGINT NOT NULL,
  PROJECTION_STATE VARCHAR(64) NOT NULL,
  KAFKA_PARTITION INT NOT NULL,
  KAFKA_OFFSET BIGINT NOT NULL,
  TRACE_ID VARCHAR(128) NOT NULL,
  SPAN_ID VARCHAR(128) NOT NULL,
  REQUEST_ID VARCHAR(128) NOT NULL,
  ENVELOPE_DIGEST VARCHAR(64) NOT NULL,
  PROJECTED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY UK_STORY13_PROJECTION_OFFSET (KAFKA_PARTITION, KAFKA_OFFSET)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
