CREATE TABLE IF NOT EXISTS STORY13_FACT (
  EVENT_ID VARCHAR(96) PRIMARY KEY,
  AGGREGATE_ID VARCHAR(128) NOT NULL,
  AGGREGATE_VERSION BIGINT NOT NULL,
  ENVELOPE_JSON JSON NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS STORY13_OUTBOX (
  EVENT_ID VARCHAR(96) PRIMARY KEY,
  ENVELOPE_JSON JSON NOT NULL,
  PUBLISHED BOOLEAN NOT NULL DEFAULT FALSE,
  KAFKA_PARTITION INT NOT NULL DEFAULT -1,
  KAFKA_OFFSET BIGINT NOT NULL DEFAULT -1,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PUBLISHED_AT TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:01',
  INDEX IDX_STORY13_OUTBOX_PUBLISHED (PUBLISHED, CREATED_AT)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS STORY13_GUARDED_COMMAND (
  COMMAND_ID VARCHAR(96) PRIMARY KEY,
  DEPENDENCY_NAME VARCHAR(64) NOT NULL,
  STATE_ADVANCED BOOLEAN NOT NULL DEFAULT FALSE,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
