package model

import (
	"fmt"
	"time"
)

// Story13Fact 表模型
// AUTOGENERATED: DO NOT EDIT
type Story13Fact struct {
	EventId          string    `gorm:"column:EVENT_ID;primaryKey;not null" json:"EventId"`
	AggregateId      string    `gorm:"column:AGGREGATE_ID" json:"AggregateId"`
	AggregateVersion int64     `gorm:"column:AGGREGATE_VERSION" json:"AggregateVersion"`
	EnvelopeJson     string    `gorm:"column:ENVELOPE_JSON" json:"EnvelopeJson"`
	CreatedAt        time.Time `gorm:"column:CREATED_AT;AUTOCREATETIME" json:"CreatedAt"`
}

// Story13FactPrimaryKey 单主键类型别名
type Story13FactPrimaryKey string

// TableName 返回表名
func (story13Fact *Story13Fact) TableName() string {
	return "STORY13_FACT"
}

// Clone 克隆对象
func (story13Fact *Story13Fact) Clone() *Story13Fact {
	if story13Fact == nil {
		return nil
	}
	return &Story13Fact{
		EventId:          story13Fact.EventId,
		AggregateId:      story13Fact.AggregateId,
		AggregateVersion: story13Fact.AggregateVersion,
		EnvelopeJson:     story13Fact.EnvelopeJson,
		CreatedAt:        story13Fact.CreatedAt,
	}
}

// ListZeroValueCols 列出零值列或非零值列
// filterPrimary: false-主键列正常处理 true-主键列被过滤掉
// filterIndex: false-索引列正常处理 true-索引列被过滤掉
// filterIsZero: false-只获取零值的列, true-只获取非零值的列
// filterSpecial: 是否过滤特殊列(jpaVersion/createTime/lastUpdateTime)
func (story13Fact *Story13Fact) ListZeroValueCols(filterPrimary bool, filterIndex bool, filterIsZero bool, filterSpecial bool) ([]string, []interface{}, error) {
	if story13Fact == nil {
		return nil, nil, fmt.Errorf("story13Fact is nil")
	}

	var cols []string
	var vals []interface{}

	// generalColZeroVal 用于普通列的零值检查，避免重复代码
	var generalColZeroVal bool = false

	// EventId - 主键，索引列
	if !filterPrimary {
		isZero := story13Fact.EventId == ""
		// false 保留零值 true 过滤零值
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "EVENT_ID")
			vals = append(vals, story13Fact.EventId)
		}
	}

	// AggregateId - 普通列
	generalColZeroVal = story13Fact.AggregateId == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "AGGREGATE_ID")
		vals = append(vals, story13Fact.AggregateId)
	}

	// AggregateVersion - 普通列
	generalColZeroVal = story13Fact.AggregateVersion == 0
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "AGGREGATE_VERSION")
		vals = append(vals, story13Fact.AggregateVersion)
	}

	// EnvelopeJson - 普通列
	generalColZeroVal = story13Fact.EnvelopeJson == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "ENVELOPE_JSON")
		vals = append(vals, story13Fact.EnvelopeJson)
	}

	// CreatedAt - 普通列
	generalColZeroVal = story13Fact.CreatedAt.IsZero()
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "CREATED_AT")
		vals = append(vals, story13Fact.CreatedAt)
	}

	return cols, vals, nil
}

// ToString 转换为字符串
func (story13Fact *Story13Fact) ToString() string {
	if story13Fact == nil {
		return ""
	}
	return fmt.Sprintf("Story13Fact:(%+v)", *story13Fact)
}

// Story13FactAllowUpdateCols 支持更新的列名列表
var Story13FactAllowUpdateCols = []string{"AGGREGATE_ID", "AGGREGATE_VERSION", "ENVELOPE_JSON"}

// Story13FactIndexLeadingCols 索引前导列，用于检查是否走了索引，避免全表扫描
// 列名必须和数据库表列名一致，区分大小写
var Story13FactIndexLeadingCols = []string{"EVENT_ID"}
