package model

import (
	"fmt"
	"time"
)

// Story13GuardedCommand 表模型
// AUTOGENERATED: DO NOT EDIT
type Story13GuardedCommand struct {
	CommandId      string    `gorm:"column:COMMAND_ID;primaryKey;not null" json:"CommandId"`
	DependencyName string    `gorm:"column:DEPENDENCY_NAME" json:"DependencyName"`
	StateAdvanced  int       `gorm:"column:STATE_ADVANCED" json:"StateAdvanced"`
	CreatedAt      time.Time `gorm:"column:CREATED_AT;AUTOCREATETIME" json:"CreatedAt"`
}

// Story13GuardedCommandPrimaryKey 单主键类型别名
type Story13GuardedCommandPrimaryKey string

// TableName 返回表名
func (story13GuardedCommand *Story13GuardedCommand) TableName() string {
	return "STORY13_GUARDED_COMMAND"
}

// Clone 克隆对象
func (story13GuardedCommand *Story13GuardedCommand) Clone() *Story13GuardedCommand {
	if story13GuardedCommand == nil {
		return nil
	}
	return &Story13GuardedCommand{
		CommandId:      story13GuardedCommand.CommandId,
		DependencyName: story13GuardedCommand.DependencyName,
		StateAdvanced:  story13GuardedCommand.StateAdvanced,
		CreatedAt:      story13GuardedCommand.CreatedAt,
	}
}

// ListZeroValueCols 列出零值列或非零值列
// filterPrimary: false-主键列正常处理 true-主键列被过滤掉
// filterIndex: false-索引列正常处理 true-索引列被过滤掉
// filterIsZero: false-只获取零值的列, true-只获取非零值的列
// filterSpecial: 是否过滤特殊列(jpaVersion/createTime/lastUpdateTime)
func (story13GuardedCommand *Story13GuardedCommand) ListZeroValueCols(filterPrimary bool, filterIndex bool, filterIsZero bool, filterSpecial bool) ([]string, []interface{}, error) {
	if story13GuardedCommand == nil {
		return nil, nil, fmt.Errorf("story13GuardedCommand is nil")
	}

	var cols []string
	var vals []interface{}

	// generalColZeroVal 用于普通列的零值检查，避免重复代码
	var generalColZeroVal bool = false

	// CommandId - 主键，索引列
	if !filterPrimary {
		isZero := story13GuardedCommand.CommandId == ""
		// false 保留零值 true 过滤零值
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "COMMAND_ID")
			vals = append(vals, story13GuardedCommand.CommandId)
		}
	}

	// DependencyName - 普通列
	generalColZeroVal = story13GuardedCommand.DependencyName == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "DEPENDENCY_NAME")
		vals = append(vals, story13GuardedCommand.DependencyName)
	}

	// StateAdvanced - 普通列
	generalColZeroVal = story13GuardedCommand.StateAdvanced == 0
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "STATE_ADVANCED")
		vals = append(vals, story13GuardedCommand.StateAdvanced)
	}

	// CreatedAt - 普通列
	generalColZeroVal = story13GuardedCommand.CreatedAt.IsZero()
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "CREATED_AT")
		vals = append(vals, story13GuardedCommand.CreatedAt)
	}

	return cols, vals, nil
}

// ToString 转换为字符串
func (story13GuardedCommand *Story13GuardedCommand) ToString() string {
	if story13GuardedCommand == nil {
		return ""
	}
	return fmt.Sprintf("Story13GuardedCommand:(%+v)", *story13GuardedCommand)
}

// Story13GuardedCommandAllowUpdateCols 支持更新的列名列表
var Story13GuardedCommandAllowUpdateCols = []string{}

// Story13GuardedCommandIndexLeadingCols 索引前导列，用于检查是否走了索引，避免全表扫描
// 列名必须和数据库表列名一致，区分大小写
var Story13GuardedCommandIndexLeadingCols = []string{"COMMAND_ID"}
