package model

import (
	"fmt"
	"time"
)

// Story13Outbox 表模型
// AUTOGENERATED: DO NOT EDIT
type Story13Outbox struct {
	EventId        string    `gorm:"column:EVENT_ID;primaryKey;not null" json:"EventId"`
	EnvelopeJson   string    `gorm:"column:ENVELOPE_JSON" json:"EnvelopeJson"`
	Published      int       `gorm:"column:PUBLISHED" json:"Published"`
	KafkaPartition int       `gorm:"column:KAFKA_PARTITION" json:"KafkaPartition"`
	KafkaOffset    int64     `gorm:"column:KAFKA_OFFSET" json:"KafkaOffset"`
	CreatedAt      time.Time `gorm:"column:CREATED_AT;AUTOCREATETIME" json:"CreatedAt"`
	PublishedAt    time.Time `gorm:"column:PUBLISHED_AT" json:"PublishedAt"`
}

// Story13OutboxPrimaryKey 单主键类型别名
type Story13OutboxPrimaryKey string

// TableName 返回表名
func (story13Outbox *Story13Outbox) TableName() string {
	return "STORY13_OUTBOX"
}

// Clone 克隆对象
func (story13Outbox *Story13Outbox) Clone() *Story13Outbox {
	if story13Outbox == nil {
		return nil
	}
	return &Story13Outbox{
		EventId:        story13Outbox.EventId,
		EnvelopeJson:   story13Outbox.EnvelopeJson,
		Published:      story13Outbox.Published,
		KafkaPartition: story13Outbox.KafkaPartition,
		KafkaOffset:    story13Outbox.KafkaOffset,
		CreatedAt:      story13Outbox.CreatedAt,
		PublishedAt:    story13Outbox.PublishedAt,
	}
}

// ListZeroValueCols 列出零值列或非零值列
// filterPrimary: false-主键列正常处理 true-主键列被过滤掉
// filterIndex: false-索引列正常处理 true-索引列被过滤掉
// filterIsZero: false-只获取零值的列, true-只获取非零值的列
// filterSpecial: 是否过滤特殊列(jpaVersion/createTime/lastUpdateTime)
func (story13Outbox *Story13Outbox) ListZeroValueCols(filterPrimary bool, filterIndex bool, filterIsZero bool, filterSpecial bool) ([]string, []interface{}, error) {
	if story13Outbox == nil {
		return nil, nil, fmt.Errorf("story13Outbox is nil")
	}

	var cols []string
	var vals []interface{}

	// generalColZeroVal 用于普通列的零值检查，避免重复代码
	var generalColZeroVal bool = false

	// EventId - 主键，索引列
	if !filterPrimary {
		isZero := story13Outbox.EventId == ""
		// false 保留零值 true 过滤零值
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "EVENT_ID")
			vals = append(vals, story13Outbox.EventId)
		}
	}

	// EnvelopeJson - 普通列
	generalColZeroVal = story13Outbox.EnvelopeJson == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "ENVELOPE_JSON")
		vals = append(vals, story13Outbox.EnvelopeJson)
	}

	// Published - 普通列
	generalColZeroVal = story13Outbox.Published == 0
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "PUBLISHED")
		vals = append(vals, story13Outbox.Published)
	}

	// KafkaPartition - 普通列
	generalColZeroVal = story13Outbox.KafkaPartition == 0
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "KAFKA_PARTITION")
		vals = append(vals, story13Outbox.KafkaPartition)
	}

	// KafkaOffset - 普通列
	generalColZeroVal = story13Outbox.KafkaOffset == 0
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "KAFKA_OFFSET")
		vals = append(vals, story13Outbox.KafkaOffset)
	}

	// CreatedAt - 普通列
	generalColZeroVal = story13Outbox.CreatedAt.IsZero()
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "CREATED_AT")
		vals = append(vals, story13Outbox.CreatedAt)
	}

	// PublishedAt - 普通列
	generalColZeroVal = story13Outbox.PublishedAt.IsZero()
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "PUBLISHED_AT")
		vals = append(vals, story13Outbox.PublishedAt)
	}

	return cols, vals, nil
}

// ToString 转换为字符串
func (story13Outbox *Story13Outbox) ToString() string {
	if story13Outbox == nil {
		return ""
	}
	return fmt.Sprintf("Story13Outbox:(%+v)", *story13Outbox)
}

// Story13OutboxAllowUpdateCols 支持更新的列名列表
var Story13OutboxAllowUpdateCols = []string{"ENVELOPE_JSON", "PUBLISHED", "KAFKA_PARTITION", "KAFKA_OFFSET", "PUBLISHED_AT"}

// Story13OutboxIndexLeadingCols 索引前导列，用于检查是否走了索引，避免全表扫描
// 列名必须和数据库表列名一致，区分大小写
var Story13OutboxIndexLeadingCols = []string{"EVENT_ID"}
