package model

import (
	"fmt"
	"time"
)

// Story13Projection 表模型
// AUTOGENERATED: DO NOT EDIT
type Story13Projection struct {
	EventId          string    `gorm:"column:EVENT_ID;primaryKey;not null" json:"EventId"`
	WorkspaceId      string    `gorm:"column:WORKSPACE_ID" json:"WorkspaceId"`
	AggregateId      string    `gorm:"column:AGGREGATE_ID" json:"AggregateId"`
	AggregateVersion int64     `gorm:"column:AGGREGATE_VERSION" json:"AggregateVersion"`
	ProjectionState  string    `gorm:"column:PROJECTION_STATE" json:"ProjectionState"`
	KafkaPartition   int       `gorm:"column:KAFKA_PARTITION" json:"KafkaPartition"`
	KafkaOffset      int64     `gorm:"column:KAFKA_OFFSET" json:"KafkaOffset"`
	TraceId          string    `gorm:"column:TRACE_ID" json:"TraceId"`
	SpanId           string    `gorm:"column:SPAN_ID" json:"SpanId"`
	RequestId        string    `gorm:"column:REQUEST_ID" json:"RequestId"`
	EnvelopeDigest   string    `gorm:"column:ENVELOPE_DIGEST" json:"EnvelopeDigest"`
	ProjectedAt      time.Time `gorm:"column:PROJECTED_AT;AUTOCREATETIME" json:"ProjectedAt"`
}

// Story13ProjectionPrimaryKey 单主键类型别名
type Story13ProjectionPrimaryKey string

// TableName 返回表名
func (story13Projection *Story13Projection) TableName() string {
	return "STORY13_PROJECTION"
}

// Clone 克隆对象
func (story13Projection *Story13Projection) Clone() *Story13Projection {
	if story13Projection == nil {
		return nil
	}
	return &Story13Projection{
		EventId:          story13Projection.EventId,
		WorkspaceId:      story13Projection.WorkspaceId,
		AggregateId:      story13Projection.AggregateId,
		AggregateVersion: story13Projection.AggregateVersion,
		ProjectionState:  story13Projection.ProjectionState,
		KafkaPartition:   story13Projection.KafkaPartition,
		KafkaOffset:      story13Projection.KafkaOffset,
		TraceId:          story13Projection.TraceId,
		SpanId:           story13Projection.SpanId,
		RequestId:        story13Projection.RequestId,
		EnvelopeDigest:   story13Projection.EnvelopeDigest,
		ProjectedAt:      story13Projection.ProjectedAt,
	}
}

// ListZeroValueCols 列出零值列或非零值列
// filterPrimary: false-主键列正常处理 true-主键列被过滤掉
// filterIndex: false-索引列正常处理 true-索引列被过滤掉
// filterIsZero: false-只获取零值的列, true-只获取非零值的列
// filterSpecial: 是否过滤特殊列(jpaVersion/createTime/lastUpdateTime)
func (story13Projection *Story13Projection) ListZeroValueCols(filterPrimary bool, filterIndex bool, filterIsZero bool, filterSpecial bool) ([]string, []interface{}, error) {
	if story13Projection == nil {
		return nil, nil, fmt.Errorf("story13Projection is nil")
	}

	var cols []string
	var vals []interface{}

	// generalColZeroVal 用于普通列的零值检查，避免重复代码
	var generalColZeroVal bool = false

	// EventId - 主键，索引列
	if !filterPrimary {
		isZero := story13Projection.EventId == ""
		// false 保留零值 true 过滤零值
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "EVENT_ID")
			vals = append(vals, story13Projection.EventId)
		}
	}

	// WorkspaceId - 普通列
	generalColZeroVal = story13Projection.WorkspaceId == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "WORKSPACE_ID")
		vals = append(vals, story13Projection.WorkspaceId)
	}

	// AggregateId - 普通列
	generalColZeroVal = story13Projection.AggregateId == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "AGGREGATE_ID")
		vals = append(vals, story13Projection.AggregateId)
	}

	// AggregateVersion - 普通列
	generalColZeroVal = story13Projection.AggregateVersion == 0
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "AGGREGATE_VERSION")
		vals = append(vals, story13Projection.AggregateVersion)
	}

	// ProjectionState - 普通列
	generalColZeroVal = story13Projection.ProjectionState == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "PROJECTION_STATE")
		vals = append(vals, story13Projection.ProjectionState)
	}

	// KafkaPartition - 普通列
	generalColZeroVal = story13Projection.KafkaPartition == 0
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "KAFKA_PARTITION")
		vals = append(vals, story13Projection.KafkaPartition)
	}

	// KafkaOffset - 普通列
	generalColZeroVal = story13Projection.KafkaOffset == 0
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "KAFKA_OFFSET")
		vals = append(vals, story13Projection.KafkaOffset)
	}

	// TraceId - 普通列
	generalColZeroVal = story13Projection.TraceId == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "TRACE_ID")
		vals = append(vals, story13Projection.TraceId)
	}

	// SpanId - 普通列
	generalColZeroVal = story13Projection.SpanId == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "SPAN_ID")
		vals = append(vals, story13Projection.SpanId)
	}

	// RequestId - 普通列
	generalColZeroVal = story13Projection.RequestId == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "REQUEST_ID")
		vals = append(vals, story13Projection.RequestId)
	}

	// EnvelopeDigest - 普通列
	generalColZeroVal = story13Projection.EnvelopeDigest == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "ENVELOPE_DIGEST")
		vals = append(vals, story13Projection.EnvelopeDigest)
	}

	// ProjectedAt - 普通列
	generalColZeroVal = story13Projection.ProjectedAt.IsZero()
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "PROJECTED_AT")
		vals = append(vals, story13Projection.ProjectedAt)
	}

	return cols, vals, nil
}

// ToString 转换为字符串
func (story13Projection *Story13Projection) ToString() string {
	if story13Projection == nil {
		return ""
	}
	return fmt.Sprintf("Story13Projection:(%+v)", *story13Projection)
}

// Story13ProjectionAllowUpdateCols 支持更新的列名列表
var Story13ProjectionAllowUpdateCols = []string{"WORKSPACE_ID", "AGGREGATE_ID", "AGGREGATE_VERSION", "PROJECTION_STATE", "KAFKA_PARTITION", "KAFKA_OFFSET", "TRACE_ID", "SPAN_ID", "REQUEST_ID", "ENVELOPE_DIGEST", "PROJECTED_AT"}

// Story13ProjectionIndexLeadingCols 索引前导列，用于检查是否走了索引，避免全表扫描
// 列名必须和数据库表列名一致，区分大小写
var Story13ProjectionIndexLeadingCols = []string{"EVENT_ID"}
