apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
  creationTimestamp: "2026-07-14T09:06:14Z"
  generation: 1
  labels:
    app: kindnet
    k8s-app: kindnet
    tier: node
  name: kindnet
  namespace: kube-system
  resourceVersion: "519"
  uid: 658d0dae-f724-4adf-ab4f-32fc09eee1a9
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kindnet
  template:
    metadata:
      labels:
        app: kindnet
        k8s-app: kindnet
        tier: node
    spec:
      containers:
      - env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: POD_SUBNET
          value: 10.244.0.0/16
        - name: CONTROL_PLANE_ENDPOINT
          value: ai-video-base002-22413-control-plane:6443
        image: docker.io/kindest/kindnetd:v20251212-v0.29.0-alpha-105-g20ccfc88
        imagePullPolicy: IfNotPresent
        name: kindnet-cni
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
        securityContext:
          capabilities:
            add:
            - NET_RAW
            - NET_ADMIN
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/cni/net.d
          name: cni-cfg
        - mountPath: /run/xtables.lock
          name: xtables-lock
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
        - mountPath: /var/run/nri
          name: nri-plugin
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kindnet
      serviceAccountName: kindnet
      terminationGracePeriodSeconds: 30
      tolerations:
      - operator: Exists
      volumes:
      - hostPath:
          path: /etc/cni/net.d
          type: ""
        name: cni-cfg
      - hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
        name: xtables-lock
      - hostPath:
          path: /lib/modules
          type: ""
        name: lib-modules
      - hostPath:
          path: /var/run/nri
          type: ""
        name: nri-plugin
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 3
  desiredNumberScheduled: 3
  numberAvailable: 3
  numberMisscheduled: 0
  numberReady: 3
  observedGeneration: 1
  updatedNumberScheduled: 3
